image: barichello/godot-ci:3.3.2

variables:
  EXPORT_NAME: JoyGodot

stages:
  - export
  - deploy

Windows:
  stage: export
  script:
    - mkdir -v -p build/windows
    - godot -v --export-debug "Windows Desktop" --path build/windows/$EXPORT_NAME.exe
    - cp -r Assets build/windows

  artifacts:
    name: $EXPORT_NAME
    paths:
      - build/windows