image: barichello/godot-ci:mono-3.3.2

variables:
  EXPORT_NAME: JoyGodot

stages:
  - export

Windows:
  stage: export
  script:
    - mkdir -v -p build/windows
    - godot -v --export-debug "Windows Desktop" --path build/windows/$EXPORT_NAME.exe
    - godot -v --export-pack "Windows Desktop" --path build/windows/$EXPORT_NAME.pck
    - cp -r Assets build/windows
  only:
    - main

  artifacts:
    name: $EXPORT_NAME
    paths:
      - build/windows